{
 "title": "Tickets Serverless CockroachDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tickets with CockroachDB Serverless",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div height=\"20%\">\n</div>\n<h1>Tickets, tickets, tickets!</h1>"
   }
  },
  {
   "title": " AppServer & DB Availability",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sql_isup{app=\"Tickets\", component=\"appserver\", instance=\"127.0.0.1:3000\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(0))/  sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Tickets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from ticketsgrafana;"
    }
   ]
  },
  {
   "title": "Tickets without Priority",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from Ticketsgrafana where id not in (select ticketsid from TicketsWithPrioritiesgrafana);"
    }
   ]
  },
  {
   "title": "Avg. Priority",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select AVG(priority) from prioritiesgrafana ;"
    }
   ]
  },
  {
   "title": "Tickets with Priority",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from Ticketsgrafana where id in (select ticketsid from TicketsWithPrioritiesgrafana);"
    }
   ]
  },
  {
   "title": "Tickets in APAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from Ticketsgrafana where origin='APAC'"
    }
   ]
  },
  {
   "title": "Tickets in AMERICAS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from Ticketsgrafana WHERE origin='AMERICAS'"
    }
   ]
  },
  {
   "title": "Tickets in EMEA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM Ticketsgrafana where origin='EMEA'"
    }
   ]
  },
  {
   "title": "SQL Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(sql_selects_count{app=\"Tickets\", component=\"appserver\"} [1m]))*15)",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum((rate(sql_inserts_count{app=\"Tickets\", component=\"appserver\"} [1m]))*15)",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum((rate(sql_updates_count{app=\"Tickets\", component=\"appserver\"} [1m]))*15)",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum((rate(sql_deletes_count{app=\"Tickets\", component=\"appserver\"} [1m]))*15)",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transactions_count{app=\"Tickets\", component=\"appserver\"} [1m])*15)",
     "legendFormat": "BEGIN"
    },
    {
     "expr": "sum(rate(sql_commits_count{app=\"Tickets\", component=\"appserver\"} [1m])*15)",
     "legendFormat": "COMMIT"
    },
    {
     "expr": "sum(rate(sql_rollbacks_count{app=\"Tickets\", component=\"appserver\"} [1m])*15)",
     "legendFormat": "ROLLBACK"
    }
   ]
  },
  {
   "title": "Connections In Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sql_connections{app=\"Tickets\"}",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m])*60)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration in ms per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"Tickets\", component=\"appserver\"}[1m]) / irate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m]))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\", status=~\"[45].*\"}[1m])",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"appserver\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=\"appserver\"} |= ``"
    }
   ]
  },
  {
   "title": "Browser Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"ttfb=\" | unwrap ttfb [$__auto]) by (app)",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"fcp=\" | unwrap fcp [$__auto]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"lcp=\" | unwrap lcp [$__auto]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Traces with DB Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "filters": [
      { "id": "a5fde9b8", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "pg-pool.connect" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 } }
 ]
}