{
 "title": "Tickets Selfhosted CockroachDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tickets",
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://storage.googleapis.com/publicstuff/a336ee58-f70d-4474-99ad-3ba40bde959f.jpeg\" height=\"100%\">"
   }
  },
  {
   "title": "Global Tickets with Priority ",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from Ticketsgrafana where id in (select ticketsid from TicketsWithPrioritiesgrafana);"
    }
   ]
  },
  {
   "title": " AppServer & DB Availability",
   "type": "canvas",
   "gridPos": { "h": 13, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sql_isup{app=\"Tickets\", dbtype=\"selfhosted\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(0))/  sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Global Tickets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from ticketsgrafana;"
    }
   ]
  },
  {
   "title": "Tickets without Priority",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from Ticketsgrafana where id not in (select ticketsid from TicketsWithPrioritiesgrafana);   "
    }
   ]
  },
  {
   "title": "Avg. Priority",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select AVG(priority) from prioritiesgrafana ;"
    }
   ]
  },
  {
   "title": "Tickets in APAC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from Ticketsgrafana where origin='APAC'"
    }
   ]
  },
  {
   "title": "Tickets in AMERICAS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from Ticketsgrafana WHERE origin='AMERICAS'"
    }
   ]
  },
  {
   "title": "Tickets in EMEA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM Ticketsgrafana where origin='EMEA'"
    }
   ]
  },
  {
   "title": "Tickets over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "TicketsInEMEA{id=\"c6b33a7d-ae88-4c27-beb3-162ca6625e56\", name=\"TicketsInEMEA\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "TicketsInAPAC{id=\"d5371272-43a7-499f-97a9-7ad59675a8c3\", name=\"TicketsInAPAC\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "TicketsInAmericas{id=\"bb07b238-b92d-4e91-be33-f041183f98cf\", name=\"TicketsInAmericas\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "GlobalTickets{id=\"c0860fb8-c917-4cc8-b84d-c1ab8ab70e1d\", name=\"GlobalTickets\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nodes CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{app=\"cockroachdb\"})",
     "legendFormat": "All instances"
    },
    {
     "expr": "count(up{app=\"cockroachdb\"} == 1)",
     "legendFormat": "Running instances (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{app=\"cockroachdb\"})",
     "legendFormat": "Live instances (instance liveness heartbeats)"
    }
   ]
  },
  {
   "title": "CPU Time CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{app=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{app=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{app=\"cockroachdb\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(sys_go_allocbytes{app=\"cockroachdb\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{app=\"cockroachdb\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{app=\"cockroachdb\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{app=\"cockroachdb\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "SQL Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(sql_selects_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum((rate(sql_inserts_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum((rate(sql_updates_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum((rate(sql_deletes_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transactions_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "BEGIN"
    },
    {
     "expr": "sum(rate(sql_commits_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "COMMIT"
    },
    {
     "expr": "sum(rate(sql_rollbacks_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "ROLLBACK"
    }
   ]
  },
  {
   "title": "Connections In Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sql_connections{app=\"Tickets\"}",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m])*60)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration in ms per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"Tickets\", component=\"appserver\"}[1m]) / irate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m]))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\", status=~\"[45].*\"}[1m])",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=~\".+\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{namespace=~\".+\"} "
    }
   ]
  },
  {
   "title": "Browser Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"ttfb=\" | unwrap ttfb [$__auto]) by (app)",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"fcp=\" | unwrap fcp [$__auto]) by (app)",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\",app_id=\"295\"} | logfmt  |= \"lcp=\" | unwrap lcp [$__auto]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Traces with DB Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "filters": [
      { "id": "a5fde9b8", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "pg-pool.connect" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 } }
 ]
}