apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ${DATABASE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${MAINTABLE}
      component: appserver  
  template:
    metadata:
      name: ${DATABASE}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '_status/vars'
        prometheus.io/port: '3000'       
      labels:
        app: ${MAINTABLE}
        component: appserver  
    spec:
      containers:
      - name: grafanaagent
        image:  grafana/agent:v0.39.1
        imagePullPolicy: Always
        command: ["/bin/grafana-agent"]
        args: ["-config.file", "/tmp/config/config.yaml", "-config.expand-env", "-enable-features", "integrations-next"]
        env:
        - name:  METRICSURL
          value: "${METRICSURL}"
        - name:  METRICSUSER
          value: '${METRICSUSER}' 
        - name: METRICSPASSWORD
          value: '${METRICSPASSWORD}'
        - name: LOGSPASSWORD
          value: '${LOGSPASSWORD}' 
        - name: LOGSURL
          value: '${LOGSURL}' 
        - name: LOGSUSER
          value: '${LOGSUSER}' 
        - name: TRACESENDPOINT
          value: '${TRACESENDPOINT}' 
        - name: TRACESUSER
          value: '${TRACESUSER}' 
        - name: TRACESPASSWORD
          value: '${TRACESPASSWORD}'
        - name: LOGFOLDER
          value: "$LOGFOLDER" 
        - name: CONFIG_FILE_PATH
          value: /tmp/config/config.yanl
        - name: PORT
          value: "${PORT}"
        - name: LOGTOCONSOLE
          value: "true"
        ports:
        - containerPort: 12345
        volumeMounts:
            - name: grafanaagent
              mountPath: /tmp/config
            - name: logs
              mountPath: $LOGFOLDER

      - name: ${DATABASE}
        image:  digitalemil/sourdough:sourdough-v0.30
        imagePullPolicy: Always
        env:
        - name: MAINTABLE
          value: "$MAINTABLE"
        - name: SECONDTABLE
          value: "${SECONDTABLE}"
        - name: STARS
          value: "${STARS}"

        - name: FAROURL
          value: https://faro-collector-prod-eu-west-2.grafana.net/collect
        - name: FAROKEY
          value: b315683f2e4bcbf36da9fded99f56af3

        - name: DATABASE_CONNECTIONSTRING
          value: "$DATABASE_CONNECTIONSTRING"
        - name: DBTYPE
          value: "$DBTYPE"
        - name: LOGFOLDER
          value: "$LOGFOLDER" 

        - name: TITLE
          value: "$TITLE"
        - name: WELCOME
          value: "$WELCOME"
        - name: CODE
          value: $CODE

        - name: COLOR
          value: "$COLOR"
        - name: BACKGROUNDCOLOR
          value: "$BACKGROUNDCOLOR"
        - name: INPUTCOLOR
          value: "$INPUTCOLOR"
        - name: LOGO
          value: "$LOGO" 
        - name: BACKGROUNDIMAGE
          value: "$BACKGROUNDIMAGE" 
        - name: CREATORFILE
          value: "$CREATORFILE" 

        - name: PORT
          value: "$PORT"
        ports:
        - containerPort: 3000
        volumeMounts:
            - name: sslrootcert
              mountPath: /tmp/cert1
            - name: sslcert
              mountPath: /tmp/cert2
            - name: sslkey
              mountPath: /tmp/cert3
            - name: logs
              mountPath: $LOGFOLDER
      volumes:
        - name: grafanaagent
          configMap:
            defaultMode: 420
            name: grafanaagent
        - name: sslrootcert
          configMap:
            defaultMode: 420
            name: sslrootcert
        - name: sslcert
          configMap:
            defaultMode: 420
            name: sslcert
        - name: sslkey
          configMap:
            defaultMode: 420
            name: sslkey 
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name:  ${DATABASE}
spec:
  selector:
    app: ${MAINTABLE}
    component: appserver 
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  sessionAffinity: None
  type: ClusterIP
