logs:
  configs:
    - clients:
          url: http://localhost:3100/loki/api/v1/push
      name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: appserver
          static_configs:
          - labels: 
              __path__: ${LOGFOLDER}/*.log
              app: appserver
            targets:
              - localhost
        - job_name: cockroachdb
          static_configs:
          - labels: 
              __path__:  /tmp/cockroachdb-logs/*.log
              app: appserver
            targets:
              - localhost
      target_config:
        sync_period: 10s
