logs:
  configs:
    - clients:
        - basic_auth:
            password: ${LOGSPASSWORD}
            username: ${LOGSUSER}
          url: ${LOGSURL}
      name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: appserver
          static_configs:
          - labels: 
              __path__: ${LOGFOLDER}/*.log
              app: appserver
            targets:
              - localhost
      target_config:
        sync_period: 10s
traces:
  configs:
    - name: default
      automatic_logging:
        backend: logs_instance
        logs_instance_name: default
        roots: true
      service_graphs:
        enabled: true
      remote_write:
        - endpoint: ${TRACESENDPOINT}
          basic_auth:
            username: ${TRACESUSER}
            password: ${TRACESPASSWORD}
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              cors:
                allowed_origins:
                  - '*'
                max_age: 7200
      tail_sampling:
        policies:
         - type: string_attribute
           string_attribute:
             key: http.target
             values:
               - ^\/(?:_status\/.*|healthcheck)$
             enabled_regex_matching: true
             invert_match: true
