{
 "title": "Selfhosted CockroachDB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://storage.googleapis.com/publicstuff/a336ee58-f70d-4474-99ad-3ba40bde959f.jpeg\" height=\"100%\">"
   }
  },
  {
   "title": "Global with Priority ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from Maintablegrafana where id in (select itemid from MaintableWithPrioritiesgrafana);"
    }
   ]
  },
  {
   "title": " AppServer & DB Availability",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sql_isup{app=\"Tickets\", dbtype=\"selfhosted\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(0))/  sum(process_start_time_seconds{app=\"Tickets\", component=\"appserver\"} or vector(1)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Global Entries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from MaintableGrafana;"
    }
   ]
  },
  {
   "title": "Without",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from MaintableGrafana where id not in (select itemid from MaintableWithSecondtableGrafana);   "
    }
   ]
  },
  {
   "title": "Avg. Priority",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select AVG(priority) from prioritiesgrafana ;"
    }
   ]
  },
  {
   "title": "In APAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from MaintableGrafana where origin='APAC'"
    }
   ]
  },
  {
   "title": "In AMERICAS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from MaintableGrafana where origin='AMERICAS'"
    }
   ]
  },
  {
   "title": "In EMEA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(id) from MaintableGrafana where origin='EMEA'"
    }
   ]
  },
  {
   "title": "Nodes CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(up{instance=~\"localhost:8.*\"})",
     "legendFormat": "All instances"
    },
    {
     "expr": "count(up{instance=~\"localhost:8.*\"} == 1)",
     "legendFormat": "Running instances (prometheus)"
    },
    {
     "expr": "min(liveness_livenodes{instance=~\"localhost:8.*\"})",
     "legendFormat": "Live instances (instance liveness heartbeats)"
    }
   ]
  },
  {
   "title": "CPU Time CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sys_cpu_user_ns{}[$__rate_interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(sys_cpu_sys_ns{app=\"cockroachdb\"}[$__rate_interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory CockroachDB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(sys_rss{instance=~\"localhost:8.*\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(sys_go_allocbytes{instance=~\"localhost:8.*\"})",
     "legendFormat": "Go Allocated"
    },
    {
     "expr": "sum(sys_go_totalbytes{instance=~\"localhost:8.*\"})",
     "legendFormat": "Go Total"
    },
    {
     "expr": "sum(sys_cgo_allocbytes{instance=~\"localhost:8.*\"})",
     "legendFormat": "CGo Allocated"
    },
    {
     "expr": "sum(sys_cgo_totalbytes{instance=~\"localhost:8.*\"})",
     "legendFormat": "CGo Total"
    }
   ]
  },
  {
   "title": "SQL Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(sql_selects_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum((rate(sql_inserts_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "INSERT"
    },
    {
     "expr": "sum((rate(sql_updates_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum((rate(sql_deletes_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m]))*15)",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transactions_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "BEGIN"
    },
    {
     "expr": "sum(rate(sql_commits_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "COMMIT"
    },
    {
     "expr": "sum(rate(sql_rollbacks_count{app=\"Tickets\", dbtype=\"selfhosted\"} [1m])*15)",
     "legendFormat": "ROLLBACK"
    }
   ]
  },
  {
   "title": "Connections In Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sql_connections{app=\"Tickets\"}",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(route) (rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m])*60)",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration in ms per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum by(route) (irate(http_request_duration_ms_sum{app=\"Tickets\", component=\"appserver\"}[1m]) / irate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\"} [1m]))",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Errors per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
   "targets": [
    {
     "expr": "rate(http_request_duration_ms_count{app=\"Tickets\", component=\"appserver\", status=~\"[45].*\"}[1m])",
     "legendFormat": "{{route}}, {{status}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=~\".+\"} |~ `(?i)error`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{app=~\".+\"} "
    }
   ]
  },
  {
   "title": "Traces with DB Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "filters": [
      {
       "id": "ed1a11b6",
       "operator": "=",
       "scope": "span",
       "tag": "db.user",
       "value": [ "root" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  }
 ]
}